spring:
  application:
    name: gateway

server:
  port: 8080

services:
  user-service:
    base-url: http://localhost:8081

management:
  endpoints:
    web:
      exposure:
        include: health,info
