spring:
  application:
    name: microservice
  config:
    import: "optional:configserver:"
  cloud:
    config:
      enabled: false
      import-check:
        enabled: false
    discovery:
      enabled: false

  datasource:
    url: jdbc:mysql://localhost:3306/microservice_db?createDatabaseIfNotExist=true
    username: root
    password:

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
