spring:
  application:
    name: user-service

  datasource:
    url: jdbc:mysql://localhost:3306/microservice_db?createDatabaseIfNotExist=true
    username: root
    password:

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false

server:
  port: 8081

management:
  endpoints:
    web:
      exposure:
        include: health,info
